'use strict';
/*
 * Writes every icon both apps ship, from tools/mark.js.
 * Run from the repo root:  node tools/build-icons.js
 */

const fs = require('fs');
const path = require('path');
const mark = require('./mark');

const root = path.join(__dirname, '..');
const write = (rel, data) => {
  const file = path.join(root, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, data);
  const size = fs.statSync(file).size;
  console.log('  ' + rel.padEnd(58) + (size / 1024).toFixed(1) + ' KB');
};

console.log('Windows');
write('desktop/build/icon.ico', mark.ico([16, 24, 32, 48, 64, 128, 256]));
write('desktop/build/icon.png', mark.png(256, mark.render(256, 'squircle')));
write('desktop/build/mark-path.txt', mark.pathData);

console.log('Android launcher');
// Legacy launcher bitmaps, still needed below API 26.
const DENSITIES = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
for (const [density, size] of Object.entries(DENSITIES)) {
  write(`mobile/app/src/main/res/mipmap-${density}/ic_launcher.png`,
    mark.png(size, mark.render(size, 'squircle')));
  write(`mobile/app/src/main/res/mipmap-${density}/ic_launcher_round.png`,
    mark.png(size, mark.render(size, 'circle')));
}

console.log('Android vectors');

const gradientStops = [
  ['0', '#55697F'],
  ['0.45', '#4E9A9B'],
  ['1', '#7FE3C4']
];

const seedArc = (() => {
  const [cx, cy] = mark.tip;
  const r = mark.seedRadius;
  // Two half-arcs, because vector drawables have no <circle>.
  return `M${cx},${cy - r} a${r},${r} 0 1,0 0,${2 * r} a${r},${r} 0 1,0 0,${-2 * r} Z`;
})();

const vectorMark = (size) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/build-icons.js — edit tools/mark.js, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="${size}dp"
    android:height="${size}dp"
    android:viewportWidth="${mark.VIEW}"
    android:viewportHeight="${mark.VIEW}">
    <path
        android:pathData="${mark.pathData}"
        android:strokeWidth="${mark.strokeWidth}"
        android:strokeLineCap="round"
        android:strokeLineJoin="round">
        <aapt:attr name="android:strokeColor">
            <gradient
                android:type="linear"
                android:startX="4" android:startY="28"
                android:endX="28" android:endY="4">
${gradientStops.map(([o, c]) =>
  `                <item android:offset="${o}" android:color="${c}" />`).join('\n')}
            </gradient>
        </aapt:attr>
    </path>
    <path
        android:pathData="${seedArc}"
        android:fillColor="#7FE3C4" />
</vector>
`;

write('mobile/app/src/main/res/drawable/ic_mark.xml', vectorMark(24));

// Adaptive foreground: same mark, inset into the 66% safe zone the launcher
// keeps after masking.
write('mobile/app/src/main/res/drawable/ic_launcher_foreground.xml', `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/build-icons.js — edit tools/mark.js, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group android:scaleX="2.05" android:scaleY="2.05"
           android:translateX="20.2" android:translateY="20.2">
        <path
            android:pathData="${mark.pathData}"
            android:strokeWidth="${mark.strokeWidth}"
            android:strokeLineCap="round"
            android:strokeLineJoin="round">
            <aapt:attr name="android:strokeColor">
                <gradient
                    android:type="linear"
                    android:startX="4" android:startY="28"
                    android:endX="28" android:endY="4">
${gradientStops.map(([o, c]) =>
  `                    <item android:offset="${o}" android:color="${c}" />`).join('\n')}
                </gradient>
            </aapt:attr>
        </path>
        <path
            android:pathData="${seedArc}"
            android:fillColor="#7FE3C4" />
    </group>
</vector>
`);

write('mobile/app/src/main/res/drawable/ic_launcher_background.xml', `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z" android:fillColor="#12172080" />
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr xmlns:aapt="http://schemas.android.com/aapt" name="android:fillColor">
            <gradient android:type="linear"
                android:startX="0" android:startY="0"
                android:endX="0" android:endY="108">
                <item android:offset="0" android:color="#181F2B" />
                <item android:offset="1" android:color="#0A0D12" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
`);

const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
`;
write('mobile/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml', adaptive);
write('mobile/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml', adaptive);

console.log('\nDone.');
